### ISSUE TITLE
When will it start?

### ISSUE THREAD

**Issue by ashishpatel26** [karpathy/LLM101n#24]
When will it start?

**Comment by fransay** [comment]
Hey friend,

I wish you could take a little time of to read thoroughly on the information in README.md of the repository.
That will be helpful. We've got hundreds if not thousands of people fix their eyes on this project. Raising issues like this is unhealthy for the  countless enthusiasts and Karpathy himself.
if you care, consider closing this issue of yours, in due time Karpathy will unleash the magic he has in stall for all.

**Comment by juniortarcisio** [comment]
"Update June 25. To clarify, the course will take some time to build. There is no specific timeline. Thank you for your interest but please do not submit Issues/PRs.", there's this comment on the readme.MD bottom.

**Comment by tetrahedronix** [comment]
As John Carmack said: 'When it's done'.
