### ISSUE TITLE
Looking forward to this course. If there is a chance, I hope to be able to participate in it.

### ISSUE THREAD

**Issue by zhurui1995** [karpathy/LLM101n#38]

**Comment by JonathanSum** [comment]
Yes. I see Andrej messaged and talked about participate LLM101n:
![image](https://github.com/user-attachments/assets/b43e337f-034b-4641-b1d0-69ef966fe991)

https://github.com/EurekaLabsAI/mlp

**Comment by ojoaomorais** [comment]
Please stop open this kind of thing. It's not an issue.

**Comment by dengyunsheng250** [comment]
> Please stop open this kind of thing. It's not an issue.

quiet agree with it
