### ISSUE TITLE
404 error on all chapter links from the readme.md

### ISSUE THREAD

**Issue by jmhill1287** [karpathy/LLM101n#40]

**Comment by GuyARoss** [comment]
```
Update June 25. To clarify, the course will take some time to build. There is no specific timeline. Thank you for your interest but please do not submit Issues/PRs.
```
https://github.com/karpathy/LLM101n/blob/master/README.md

```
Today, we are heads down building LLM101n, but we look forward to a future where AI is a key technology for increasing human potential. What would you like to learn?
```
https://x.com/karpathy/status/1813263734707790301

**Comment by ytang-habana** [comment]
This is nothing there

**Comment by mratanusarkar** [comment]
we should close this issue, let @karpathy work, and push something first!
it's so funny & ridiculous seeing so many issues and PRs on a blank repo!

**Comment by panamantis** [comment]
If you create a 404 Issue, you have failed your first assignment and need to be a better student in the future.  In the meantime, go to the discord channel and earn back some grades by HELPING TO ANSWER someone else's next question:  https://discord.gg/3zy8kqD9Cp

**Comment by jmhill1287** [comment]
I take my reprimand and closed!
